### ISSUE TITLE
Favorite doesn't update

### ISSUE THREAD

**Issue by itsmhamza** [HarshAndroid/MusicPlayer#1]
When I unmark the favorite button in Player Activity the favorite Adopter doesn't update please fix this

**Comment by HarshAndroid** [comment]
Refer my GitHub codes they are upgraded as well as include new features.
https://github.com/HarshAndroid/MusicPlayer

**Comment by HarshAndroid** [comment]
Can you share me a short video proof related to it or some steps to re-generate this issue (in bit details).

**Comment by itsmhamza** [comment]
kindly u can share your whatsapp no bro

**Comment by HarshAndroid** [comment]
Whatsapp me at +91 9930571502
