### ISSUE TITLE
New useful feature

### ISSUE THREAD

**Issue by StrangeCurious** [HarshAndroid/MusicPlayer#5]
This is a feature improvement which will be very useful.
You can add add play, pause, next buttons in the notification. There is only seekbar which is present.
So there will be no need to open app again and again.

I am using the latest android 13.

**Comment by HarshAndroid** [comment]
Actually I've added added play & pause button in notification but I guess it's only working till Android 12.

For Android 13, we need to use media session properly to create this features but currently I'm having quite a busy schedule to work on this, so if you can research and try to implement (if done, let me know so we can merge it into this app).

**Comment by StrangeCurious** [comment]
Sure
