### ISSUE TITLE
After Publish app not working

### ISSUE THREAD

**Issue by rajpakira24** [HarshAndroid/MusicPlayer#6]
When I test it from Android Studio it works properly. Then I uploaded this app to the Indus Appstore after customizing but after I downloaded it from their store it did not work and after some time it crashed

https://github.com/HarshAndroid/MusicPlayer-Android-Kotlin/assets/58460022/e6d69099-f434-4bf9-8cca-2fcbb65c8e4c

**Comment by HarshAndroid** [comment]
I've updated the source codes to support latest android updates.
Now you can test and let me know.

**Comment by rajpakira24** [comment]
bhaiya not working same problem
https://www.amazon.com/gp/product/B0D1F8K41G
